{% set name = "git-fame" %}
{% set version = "3.1.0" %}
{% set python_min = "3.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 7751f38b004f2faf099fca80754b77b0e79f9f295bd502f687d17fc02dd248f4

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - git-fame = gitfame:main

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - setuptools_scm >=3.4
    - toml
  run:
    - python >={{ python_min }}
    - setuptools
    - argopt >=0.3.5
    - tabulate
    - tqdm >=4.44.0

test:
  imports:
    - gitfame
  commands:
    - git-fame -v
    - git-fame -h
  requires:
    - python {{ python_min }}

about:
  home: https://github.com/casperdcl/git-fame
  license: MPL-2.0
  license_family: MOZILLA
  license_file: LICENCE
  summary: Pretty-print git repository collaborators sorted by contributions

extra:
  recipe-maintainers:
    - casperdcl
