{% set name = "git-fame" %}
{% set version = "2.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 5e3cbb5d0de80c55c0d07d629f0495bd1eae63b4438787038d0863ea43a3e91e

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - git-fame = gitfame:main

requirements:
  host:
    - python >=2.7
    - pip
    - setuptools_scm >=3.4
    - toml
  run:
    - python >=2.7
    - setuptools
    - argopt >=0.3.5
    - tabulate
    - tqdm >=4.44.0

test:
  imports:
    - gitfame
  commands:
    - git-fame -v
    - git-fame -h

about:
  home: https://github.com/casperdcl/git-fame
  license: MPL-2.0
  license_family: MOZILLA
  license_file: LICENCE
  summary: Pretty-print git repository collaborators sorted by contributions

extra:
  recipe-maintainers:
    - casperdcl
