{% set name = "git-fame" %}
{% set version = "2.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: be72b64af451d887099339848fe310e686f2bd472bbde7e4fc338825c364bf2d

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - git-fame = gitfame:main

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools_scm >=3.4
    - toml
  run:
    - python >={{ python_min }}
    - setuptools
    - argopt >=0.3.5
    - tabulate
    - tqdm >=4.44.0

test:
  requires:
    - python {{ python_min }}
  imports:
    - gitfame
  commands:
    - git-fame -v
    - git-fame -h

about:
  home: https://github.com/casperdcl/git-fame
  license: MPL-2.0
  license_family: MOZILLA
  license_file: LICENCE
  summary: Pretty-print git repository collaborators sorted by contributions

extra:
  recipe-maintainers:
    - casperdcl
